DROTH 2627 Interface typos
finnishtransportagency/digiroad2 pull request #1629
Opened 2021-02-19 09:29 UTC by annarik

https://extranet.vayla.fi/jira/browse/DROTH-2627
Testit ok http://livibuild04.vally.local/jenkins/job/oth/job/Run-Tests/652/

2021-02-19 09:36 UTC, sasuolanderSito commented on UI/src/view/initialPopupView.js
> +                        '<p>' + "Tietolaji" + '<span class="assetTypeText">' + defaultAsset + '</span>' + '</p>'+
Joo, nää pitäis mieluummin tulla jostakin lang conf tiedostosta kuin kovakoodata tänne mut minkäs voi. Yksi kieli vaatimuksena, joten ei tavallaan haittaa.  Toivotaan että ruotsinkieliset kunnat ei ala vaatia kääntämistä.

2021-02-19 09:36 UTC, sasuolanderSito approved these changes

2021-02-19 12:52 UTC, sasuolanderSito requested changes
odotetaan sitä flyway

2021-02-22 09:10 UTC, sasuolanderSito approved these changes
ok

2021-02-22 10:29 UTC, annarik commented
Testit ajettu uudelleen (OK).

2021-02-22 11:06 UTC, merged