Droth 2708 prohibition service empty list error
finnishtransportagency/digiroad2 pull request #1634
Opened 2021-03-11 10:53 UTC by annarik

https://extranet.vayla.fi/jira/browse/DROTH-2708

2021-03-11 11:08 UTC, sasuolanderSito requested changes

2021-03-11 11:08 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/ProhibitionService.scala
> +      .getOrElse(throw new IllegalStateException("Old asset " + adjustment.assetId + " of type " + adjustment.typeId + " no longer available"))
Tässä ton tyypin kertominen ei kyl oo tarpeellinen. Tää on ProhibitionService, joten kertoo jo minkä tyyppinen asset on käsittelyssä. Itse viesti voisi kyl ilmaista että on Prohibition kyseessä niin erottuu noista geneerisistä.

2021-03-11 13:56 UTC, sasuolanderSito approved these changes
ok

2021-03-12 06:48 UTC, annarik commented
Testit ok.

2021-03-12 08:03 UTC, merged