Droth-2759 delete integration auth strategy
finnishtransportagency/digiroad2 pull request #1708
Opened 2021-05-27 12:38 UTC by annarik

https://extranet.vayla.fi/jira/browse/DROTH-2759

2021-05-27 12:41 UTC, AnttiJokela approved these changes

2021-05-27 12:47 UTC, sasuolanderSito commented
tuolla CICD skriptissä on noita authentication_basic env hommia myös

2021-06-01 05:45 UTC, sasuolanderSito requested changes
![image](https://user-images.githubusercontent.com/70522354/120272317-8ddef380-c2b5-11eb-98ee-31308b2569db.png)
https://github.com/finnishtransportagency/digiroad2/blob/1ed6761c66fd5526a56c134578a0d275b5cb896a/digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/IntegrationApiSpec.scala


Sun pitää käydä testit läpi viellä.

2021-06-01 10:05 UTC, sasuolanderSito requested changes
Vaatii korjailu, katotaan yhdessä

2021-06-01 10:05 UTC, sasuolanderSito commented on digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/IntegrationApiSpec.scala
> -  test("Get assets requires municipality number") {
sä et oikein saisi tehdä näin. Nää on valideja testejä. Sun pitää poistaa authentican osa tosta vain

2021-06-01 10:05 UTC, sasuolanderSito commented on digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/MunicipalityApiRequestSpec.scala
> -    putJsonWithUserAuth("/" + "assetUpdateFromAWS", payLoad.getBytes, getAuthorizationHeader("kalpa", "kalpa")) {
tää vaatii tarkistusta

2021-06-01 10:05 UTC, sasuolanderSito commented on digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/ServiceRoadApiSpec.scala
> -  test("Get all existing active assets by poligon in database") {
Ei näin

2021-06-01 10:05 UTC, sasuolanderSito commented on digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ServiceRoadAPI.scala
> -  override val realm: String = "Service Road API"
miksi tämä piti poistaa?

2021-06-01 10:05 UTC, sasuolanderSito commented on digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/MunicipalityApi.scala
> -  override val realm: String = "Municipality API"
miksi tämä piti poistaa?

2021-06-02 06:52 UTC, sasuolanderSito requested changes
Vähän vois viel tarkistella.

2021-06-02 06:52 UTC, sasuolanderSito commented on digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/ServiceRoadApiSpec.scala
>    test("Should require correct authentication", Tag("db")) {
Varmaan olis hyvä tarkistaa että nää test nimet on yhä loogisia, tän testin varmaan voi poistaa, toi ei taida edes mennä läpi kun toi olettaa Unauthorized ja nyt se saa 200 kun ei ole mitään authentication tossa välissä

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

2021-06-02 06:52 UTC, sasuolanderSito commented on digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/IntegrationApiSpec.scala
>    test("Should require correct authentication", Tag("db")) {
Tää ei myöskään mene enään läpi. Tätä testiä ei myöskään tarvita.

2021-06-02 11:00 UTC, sasuolanderSito approved these changes
ok

2021-06-02 11:34 UTC, merged