Droth 2660 new lane creation
finnishtransportagency/digiroad2 pull request #1774
Opened 2021-08-19 06:41 UTC by sasuolanderSito

tää on tälläinen osa 1,ehkä voi merge tai tehdään loppuun tässä kun muut osat valmiina,

vähän meni copy paste nyt toi create, tossa on toi m arvojen haku linkkien avulla, se ehkä on turha kun eikös ne tiedot tuu tossa muutostiedossa myös.

2021-08-19 09:13 UTC, AnttiJokela requested changes

2021-08-19 09:13 UTC, AnttiJokela commented on digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/Lane.scala
>  case class NewIncomeLane ( id: Long, startMeasure: Double, endMeasure: Double, municipalityCode : Long,
Income on muuten tulo rahamielessä, tämän voisi nimetä uudelleen.

2021-08-19 09:13 UTC, AnttiJokela commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/AutomaticLaneCreationModificationProcess.scala
> +        //Kevarit (roadNumbers(tie) 70000 - 99999): Lane Code (Kaistat) 31
ei suomea kommentteihin.

2021-08-19 09:13 UTC, AnttiJokela commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/AutomaticLaneCreationModificationProcess.scala
> +      def laneCodeAndSideCode(source: Source): (Int, Int) = {
Eikös side code ole suhteessa linkin digitointisuuntaan, sitä ei voi päätellä viitteen datan perusteella..

2021-08-19 09:13 UTC, AnttiJokela commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/AutomaticLaneCreationModificationProcess.scala
> +            NewIncomeLane(0, startMeasure = source.startAddrMValue,
AddrMValue on nyt osoitteen m-arvo (etäisyys tieosan alusta). Sitä ei voi käyttää linkillä osittamaan linkin pituutta, niinkun tässä nyt tapahtuu.

Viitteen tietojen perusteella pitää VKM:stä hakea uuden osoiteen linkit ja tallentaa kaistat niiden mukaan.

2021-08-19 10:09 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/AutomaticLaneCreationModificationProcess.scala
> +      def laneCodeAndSideCode(source: Source): (Int, Int) = {
toi tapahtuis sen mukaan mikä kaista koodi on

2021-08-19 10:22 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/AutomaticLaneCreationModificationProcess.scala
> +      def laneCodeAndSideCode(source: Source): (Int, Int) = {
kun kaista koodin ensimmäinen numero määritti mihin suuntaan se menee

2021-08-24 13:30 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/AutomaticLaneCreationModificationProcess.scala
> +      def laneCodeAndSideCode(source: Source): (Int, Int) = {
![image](https://user-images.githubusercontent.com/70522354/130625091-47e933ff-2de0-4400-b0e6-3cb3273a3603.png)
täälä on kyl tälläinen kaava joka menee ajoratan ja kaistakoodin mukaan

2021-09-09 06:12 UTC, sasuolanderSito commented
ei toteuta

2021-09-09 06:12 UTC, closed without merging