Droth 3062 update lanes when traffic direction is updated
finnishtransportagency/digiroad2 pull request #1852
Opened 2022-01-19 12:25 UTC by SWJPTulijoki

Toiminto kaistojen päivittämiseen liikennesuunnan muutoksen jälkeen. Toimii yksi- ja kaksikaistaisilla teillä. Jos käytössä olevien kaistojen määrä on eri, niin toiminnallisuutta ei suoriteta.

Kaksikaistaiset tiet:

Muutos kaksisuuntaisesta yksisuuntaiseksi (muutettavien kaistojen määrä = 1): Vastakkaisen kaistan tilalle uuden liikennesuunnan mukainen lisäkaista.

Yksisuuntaisen suunnan kääntö (muutettavien kaistojen määrä = 2): Molempien kaistojen tilalle uuden suunnan mukaiset kaistat (pääkaista ja lisäkaista).

Yksisuuntaiset tiet: Vanhan kaistan tilalle uuden liikennesuunnan mukainen lisäkaista.

Kaistojen luonti:
* lisäkaistat lanecodella 2
* tarkistetaan, onko käyttötarkoitukseen sopivaa expiroitua kaistaa
* kaistan muut tiedot (alkupiste, loppupiste yms.) kopioidaan expiroitavasta kaistasta

Testit testaavat kuusi eri tapausta uuden kaistan luonnilla sekä kaksi tapausta kaistan uudelleen käyttöönotolla. Lisäksi testataan, että kaistamuutoksia ei tehdä, jos liikennesuuntaa ei muuteta (eli muutetaan hallinnollista luokkaa tms.)

2022-01-19 12:38 UTC, sasuolanderSito commented on digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala
> +      val lanesTowardsDigitizing = lanesAfterUpdate.filter(lane => lane.sideCode == 2)
meillä tais olla enum tyyppinen homma noille numeroille

2022-01-19 12:39 UTC, sasuolanderSito commented on digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala
> +      expiredLane.getOrElse(null).sideCode should be(3)
ei heitellä null arvoja, option ja none ja niiden kaa isDefined tarkistus

2022-01-19 12:40 UTC, sasuolanderSito commented on digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala
> +      ServiceWithDao.create(Seq(NewLane(0, 0, 500, 745, false, false, lanePropertiesValues2)), Set(999L), 2, usernameTest)
kannataa välttää copy paste

2022-01-19 12:42 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
> +    if (propertyName == "traffic_direction") {
RoadLinkDAO.TrafficDirection

2022-01-19 12:47 UTC, sasuolanderSito requested changes
kun kaistoja expirataan pitää aina siirtää vanha kaista historia tauluun, en ole varma poistetaanko expirattu päätaulusta mut muistelisin että niin tehdään.

Jos tämä vaatii juuri tälläistä toteutusta niin pitäisi ehkä vähän miettiä uudestaan historiointia. 
Toinen asia että tuntematon ei expiraa kaistaa. En nyt muista heti millä käyttäjänimellä expirataan.

2022-01-19 13:03 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
> +  lazy val laneService = new LaneService(this, eventbus)
eikös tää pidä injectoida kontruktorissa, ja tää on vähän öö miksi roadlinkService tarvii laneService

2022-01-19 13:07 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
> +    if (propertyName == "traffic_direction") {
Isompi kysymys miksi juuri tähän setLinkProperty kohtaan tää lisätty, jonnekin ylemmäs tämä kuuluisi
updateLinkProperties vois olla parempi, tuolla vähän ylempänä

2022-01-19 13:13 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
> +    val lanesInUse = allLanes.filter(lane => lane.expired == false)
```suggestion
    val lanesInUse = allLanes.filter(_.expired == false)
```

2022-01-19 13:21 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
> +    if (lanesInUse.size == 2) {
eikös käytössö olevia kaistoja voi olla enemmän kuin 2,mitäs silloin tapahtuu?

2022-01-19 13:30 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
> +        val laneToExpire = lanesInUse.find(lane => lane.laneCode != 1)
```suggestion
        val laneToExpire = lanesInUse.find(lane => lane.laneCode != LaneNumberOneDigit.MainLane.laneCode)
```

2022-01-19 13:32 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
> +    def processLaneChanges(laneToExpire: PersistedLane, newSideCode: Int, newLaneCode: Int) = {
```suggestion
    def processLaneChanges(laneToExpire: PersistedLane, newSideCode: SideCode, newLaneCode: Int) = {
```
newLaneCode vois olla tyyppiä LaneNumberOneDigit mut ei ehkä oo tarpeen

2022-01-19 13:33 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
> +      dao.expireLaneByLaneId(laneToExpire.id, username)
moveIntoHistory() tulis varmaan tähän

2022-01-19 13:37 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/lane/LaneDao.scala
> +  def reuseExpiredLane(laneId: Long) = {
mitä tämä tekee ?, täähän ei palauta mitään

2022-01-19 13:41 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
> +          dao.reuseExpiredLane(lane.id)
eikös tää nyt riko muutoshitoriaa jos jo poistettu kaista syntyy uudestaan, vanha pitäisi varmaan kopioida ja sen pohjalta luoda uusi uudella id

2022-01-19 13:47 UTC, SWJPTulijoki commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
> +    if (lanesInUse.size == 2) {
Voi olla. Määrittelyssä on kuitenkin vain 1- ja 2-kaistaiset. Pelkästä liikennesuunnan muutoksesta ei pysty suoraan päätteleen mitä kaistoille tulisi tehdä useampikaistaisilla teillä. Jos tähän halutaan jokin automaattinen toiminto, niin pitäisi varmaan määritellä jokin vakioratkaisu, jonka mukaan muokataan kaikki? Käytännössä varmaan useampikaistaisilla kaistamuutokset pitää tehdä nykytilanteessa käsin.

2022-01-19 13:56 UTC, SWJPTulijoki commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
> +    def processLaneChanges(laneToExpire: PersistedLane, newSideCode: Int, newLaneCode: Int) = {
Hmm, PersistedLane-luokassa sidecode on kuitenkin tyyppiä Int eikä toi Sidecode enum?

2022-01-19 14:03 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
> +    def processLaneChanges(laneToExpire: PersistedLane, newSideCode: Int, newLaneCode: Int) = {
siis ajatuksena on piilottaa mystiset numerot piiloon ja sitten käyttää niitä numeroita kun on tarvetta.
jolloin toi ottaisi sisään SideCode.BothDirections vaikkapa ja se sitten muunetaan numeroksi  BothDirections.value kun mennään dao luokkaan

2022-01-31 07:19 UTC, closed without merging

2022-01-31 07:21 UTC, SWJPTulijoki commented
Kyseinen task palautettu määrittelyyn.