DROTH-3198 Refactored roadLink enriching and added batch for filling …
finnishtransportagency/digiroad2 pull request #1954
Opened 2022-04-21 07:04 UTC by anttiahopeltositowise

Refaktoroitu enrichRoadLink, tielinkkien ominaisuustietoja ei generoida (täten ei myöskään päivitetä incompleteLink taulua) ja samuuteta enää selailuin ja hakujen yhteydessä, vaan se hoituu päivittäisessä UpdateIncompleteLinkList-batchissa. Luotu oma eräajo cachen täyttämistä varten. Tielinkkien ominaisuustiedot päivitetään ja samuutetaan tämänkin yhteydessä, sekä cachen Time-to-live päivitetään datalle kun dataa kysytään

2022-04-21 07:30 UTC, anttiahopeltositowise commented
UpdateIncompleteLinkList eräajolle voisi ehkä keksiä uuden nimen kuvaamaan paremmin sen roolia (generoida ominaisuustietoja linkeille kun mahdollista, samuuttaa näitä tietoja muutosten tullessa, ja täyttää incompleteLink taulua niillä linkeillä, joille ei voitu generoida tietoja VVH:n tietojen perusteella)

2022-04-21 07:43 UTC, SWJPTulijoki commented on digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/AssetDataImporterSpec.scala
> +    val mockRoadLinkService = MockitoSugar.mock[RoadLinkService]
Onko tähän joku erityinen syy, et mockit alustetaan erikseen eri testeissä?

2022-04-21 07:48 UTC, SWJPTulijoki commented on digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/util/RefreshRoadLinkCache.scala
> +    PostGISDatabase.withDynSession {
Tarvitseeko tässä olla kaksi sessiota?

2022-04-21 09:00 UTC, anttiahopeltositowise commented on digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/util/RefreshRoadLinkCache.scala
> +    PostGISDatabase.withDynSession {
Joo ei taida olla mitään syytä olla kahta sessiota. Sisällytän samaan

2022-04-21 09:02 UTC, anttiahopeltositowise commented on digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/AssetDataImporterSpec.scala
> +    val mockRoadLinkService = MockitoSugar.mock[RoadLinkService]
Jäänne, voisihan noista toistoa joskus poistaa, mutta en ottanut nyt hommaksi

2022-04-25 05:28 UTC, sasuolanderSito requested changes
Batch voitaisiin keskistää samaan paikkaan kuin muutkin batch systeemit.  Voidaan poistaa toi Digiroad2Context käyttö myös kun sitä taidettiin tarvita ton event bus systeemin käytön takia.

Tää RefreshRoadLinkCache vaatis varmaan ton startup.sh skriptin päivittämistä.

Update incompleLink List batch rikkoo yhä sitä kuuluisaa single responsibility prinsiple. Yhä täytetään cache ja päivitetään täydennetty lista. Mieluummin jaetaan selvästi roolit kun muuten  voi tulla yllättäviä yllätyksiä kun asioita saatetaan unohtaa tai nopeasti katotaan mitä metodi sanoo tekevänsä.

Olisi parempi minusta tuoda kaikki kaikki tarvittava logiikka suoraan UpdateIncompleteLinkList.scala eikä vaan kutsua getRoadLinksFromVvhAndUpdateProperties toistuvasti.

Voidaan varmaan tehdä tarvittavia metodeja roadlinkService jotta ei tarvii alkaa siirellä testejä. Niitä vaikutaa olevan jonkin verran.

2022-04-25 06:11 UTC, anttiahopeltositowise commented
Cachen täyttäminen erillisessä batchissa voisi jättää tekemättä, viime viikon Lakapa päivitys oli sujunut OK vaikka joutui itse täyttämään cachen, joten ei vaikuta pakolliselta toimenpiteeltä.

2022-04-26 06:27 UTC, anttiahopeltositowise commented
Batch siirretty nyt ajettavaksi DataFixturesta, pitää muokata AddJobToQueue lambdaa tätä varten. Jos halutaan lisätä batch jonoon lambdan kauttaa kun mergetty dev/qa niin pitää muokata lambdan koodia hieman, tai ajetaan käsin kunnes muutos kaikissa ympäristöissä. Erillinen cachen täyttö poistettu nyt, kun ei vaikuta pakolliselta. Siirretty roadLink properties generointi yms. UpdateIncompleteLinkList.scala

2022-04-26 06:34 UTC, sasuolanderSito commented on digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/RoadLinkServiceSpec.scala
> +  ignore("Changes should cause event") {
miksi ei poisteta jos vaan ignore ilman kommentia

2022-04-26 06:36 UTC, sasuolanderSito commented on digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/RoadLinkServiceSpec.scala
> +  ignore("Only road links with construction type 'in use' should be saved to incomplete_link table (not 'under construction' or 'planned')") {
eikös tää ole yhä validi testi

2022-04-26 06:36 UTC, sasuolanderSito commented on digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/RoadLinkServiceSpec.scala
> +  ignore("Should not save links to incomplete_link when the road source is not normal") {
eikös tää ole yhä validi testi

2022-04-26 06:38 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/CacheClient.scala
> +
nitpick, tyhjä rivi taisi jäädä

2022-04-26 06:40 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/UpdateIncompleteLinkList.scala
> +    * It also passes updated links and incomplete links to be saved to db by actor.
tää ei taida pitää enään paikkaansa

2022-04-26 06:42 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/UpdateIncompleteLinkList.scala
> +    LogUtils.time(logger,"Get roadlink with cache")(
jos cache ei täytetä pitäisi varmaan käyttää toista metodia, riittäistkö jos tässä tehdään se vvh haku ja sen vastaus sitten tonne enrichAndGenerateProperties

2022-04-26 06:44 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/UpdateIncompleteLinkList.scala
> +    completeLinks ++ autoGeneratedLinks ++ changedLinks ++ stillIncompleteLinks
varmaan riittää että palautetaan vaan lista id ja sen pituus

2022-04-26 06:44 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/UpdateIncompleteLinkList.scala
> +    completeLinks ++ autoGeneratedLinks ++ changedLinks ++ stillIncompleteLinks
tai vaan listan pituus

2022-04-26 06:44 UTC, anttiahopeltositowise commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/UpdateIncompleteLinkList.scala
> +    * It also passes updated links and incomplete links to be saved to db by actor.
Viimeinen lause valhetta totta

2022-04-26 07:59 UTC, anttiahopeltositowise commented on digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/RoadLinkServiceSpec.scala
> +  ignore("Only road links with construction type 'in use' should be saved to incomplete_link table (not 'under construction' or 'planned')") {
Joo, voidaan muokata tarkistamaan, että että oikeanlainen  RoadLinkChangeSet mennyt tallennukseen. Scala Objectin mockaaminen ei onnistu suoraan Mockitolla, vielä en ole saanut toimimaan, tämä pitäisi ilmeisesti olla ratkaisu https://github.com/mockito/mockito-scala#mocking-scala-object

2022-04-26 12:27 UTC, anttiahopeltositowise commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/UpdateIncompleteLinkList.scala
> +    completeLinks ++ autoGeneratedLinks ++ changedLinks ++ stillIncompleteLinks
Unit testejä rakennettu tän paluuarvoja hyödyntäen. Ei kannata muuttaa

2022-04-27 06:38 UTC, anttiahopeltositowise commented
Tehty muutoksia eilisen weeklyn jälkeen. UpdateIncompleteLinkList ei käytä cachea enää, lisätty batch RefreshRoadLinkCache, joka tyhjentää ja sitten täyttää cachen. RefreshRoadLinkCache ei generoi properties tielinkeille vaan käyttää UpdateIncompleLinkListin luomaa tietoa, koska perjantaina ei tule VVH:sta muutoksia linkeille. Tuotanto eräajot pitäisi siirtää tuotantotilille, jotta saadaan yhteys tuotanto cacheen

2022-04-27 06:40 UTC, anttiahopeltositowise commented on digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/RoadLinkServiceSpec.scala
> +  ignore("Only road links with construction type 'in use' should be saved to incomplete_link table (not 'under construction' or 'planned')") {
Jätin nää kaksi testiä nyt ignoreen kun en saa mockitoa nyt toimimaan tässä uudessa versiossa ilman actoria. Ei kovin tärkeä testi muutenkaan kun käytännössä testaa yhden .filter toiminnan vaan.

2022-04-27 06:47 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/UpdateIncompleteLinkList.scala
> +    LogUtils.time(logger, s"updateRoadLinkChanges updateIncompleteLinks incompleteLinks: ${roadLinkChangeSet.incompleteLinks.size},") {
updateRoadLinkChanges osuus voi olla vähän turhaa nyt kun tota ei ajeta tossa Akka jolloin oli hankalaa muistaa missä jotakin lopulta ajetaan

2022-04-27 06:51 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
> +  def reloadRoadLinksWithComplementaryAndChangesFromVVH(municipalities: Int, updateProperties: Boolean = false): (Seq[RoadLink], Seq[ChangeInfo], Seq[RoadLink])= {
varmaan voisi jakaa kahteen metodiin jolloin ei tarvii muistaa laittaa boolean muutujaa kun toi boolean muuttaa toimintaa aika perusteellisesti

2022-04-27 06:53 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
> +        (enrichAndGenerateProperties(links, changes), changes, enrichAndGenerateProperties(complementaryLinks, changes))
IDE varmaan auttaa heittämään oikeaan paikkaan mut voi tulla ihmettelyä miksi tätä ei löydy täältä RoadLinkService.scala

2022-04-27 06:53 UTC, anttiahopeltositowise commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/UpdateIncompleteLinkList.scala
> +    LogUtils.time(logger, s"updateRoadLinkChanges updateIncompleteLinks incompleteLinks: ${roadLinkChangeSet.incompleteLinks.size},") {
Ok omasta mielestä, helpottaa kun on selkeästi jaoteltu toiminta omiin funktioihin. Ei kasva tuon enrichAndGenerateProperties funktion pituuskaan liian suureksi

2022-04-27 06:54 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
> +        (enrichAndGenerateProperties(links, changes), changes, enrichAndGenerateProperties(complementaryLinks, changes))
enrichAndGenerateProperties varmaan voi muuttaa vain generateProperties jos poistutaan tosta boolean hommasta

2022-04-27 07:04 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/UpdateIncompleteLinkList.scala
> +    LogUtils.time(logger, s"updateRoadLinkChanges updateIncompleteLinks incompleteLinks: ${roadLinkChangeSet.incompleteLinks.size},") {
LogUtils.time(logger, s"updateRoadLinkChanges updateIncompleteLinks incompleteLinks: litania tarkoitin

2022-04-27 07:10 UTC, sasuolanderSito commented
siitä startup.sh skriptistä varmaan voi poistaa sen updateIncomplete kohdan sitä ei näiden muutoksien jälkeen tarvita

2022-04-27 08:04 UTC, sasuolanderSito commented on digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/RoadLinkServiceSpec.scala
> +  ignore("Only road links with construction type 'in use' should be saved to incomplete_link table (not 'under construction' or 'planned')") {
hyym selvempää olisi poistaa kuin ignoorata

2022-04-27 08:11 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
> +  def updateIncompleteLinks(incompleteLinks: Seq[IncompleteLink]): Unit = {
varmaan tän voisi siirtää tonne update incompletelinklist batch tiedostoon samoin noi muutkin updateRoadLinkChanges sisäiset metodit kun niitä ei käytetä muualla mut ei nyt sinäänsä haittaa kun nyt säilyy historia paremmin

2022-04-27 08:13 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/RefreshRoadLinkCache.scala
> +      val flushSuccess = LogUtils.time(logger, "Flushing cache"){
timer tässä kun flush voi ehkä olla vähän turha mut ei nyt varmaan haitaa myöskään

2022-04-27 08:16 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/RefreshRoadLinkCache.scala
> +        logger.info("Cached " + roadLinks.size + "roadlinks with updated properties")
"roadlinks with updated properties" -> "roadlinks with overrided properties from database" vois ehkä olla parempi.

2022-04-27 08:18 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/UpdateIncompleteLinkList.scala
> +import fi.liikennevirasto.digiroad2.client.Caching
import voi varmaan optimisoida

2022-04-27 08:21 UTC, sasuolanderSito approved these changes
koodi vaikutaa ok, sit kun viel nextRelease pitää olla tarkka että vain halutut muutokset menee sinne kun tää taidettiin aloittaa tosta AwsPostgis Branch

2022-04-27 10:57 UTC, closed without merging

2022-04-27 10:58 UTC, anttiahopeltositowise commented
Tehty uusi branch masterista ja mergetty https://github.com/finnishtransportagency/digiroad2/pull/1957 pullarissa.