DROTH-3251 linear asset updates from akka to batches
finnishtransportagency/digiroad2 pull request #1995
Opened 2022-06-01 06:20 UTC by SWJPTulijoki

Siirretty tielinkkien haun yhteydessä tapahtuva lineaaristen assettien samuutus eräajoiksi eli poistettu haun yhteydessä julkaistut akka actor -viestit ja niiden kuuntelu Digiroad2Contextissa. Speedlimitservicen create-metodien purgeunknown-viestit jätetty ennalleen. Linkkien haun yhteydessä oleva filltopology ajetaan normaalisti.

2022-06-01 06:45 UTC, sasuolanderSito reviewed
Hyym näitä samuutus hommia on jonkin verran nyt tuolla DataFixture tiedostosa ja ne kaikki liittyy samaan asiaan. Vois niputtee johonkin erilliseen samuutus Object joka ottaa parametrina tyypin. Pysyis homma vähän selvempänä.

2022-06-01 07:01 UTC, sasuolanderSito requested changes
Täälä tehdään yhä samuutuksen valmustelevia operaatioita noissa service luokissa. Ne voidaan poistaa turhina. Kato onko tarvetta hakea vvh change ja jos ei ole tarvetta vaihda sellaiseen jossa sitä ei enään haeta. 
Esim val (filledTopology, changeSet) = SpeedLimitFiller.fillTopology(topology, speedLimits, Some(projectedChangeSet))

2022-06-17 12:32 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LinearAssetUpdater.scala
> +    new DigiroadEventBus
tähän new DummyEventBus, ei tarvita oikeaa

2022-06-17 12:46 UTC, SWJPTulijoki commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LinearAssetUpdater.scala
> +    new DigiroadEventBus
vaihdettu

2022-06-23 15:51 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
> +import fi.liikennevirasto.digiroad2.asset.{HeightLimit, WidthLimit, CyclingAndWalking, _}
Vaikuttaa turhal muutokselta

2022-06-23 15:54 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LinearAssetUpdateProcess.scala
> +      case e => logger.error(s"Updating asset $typeId in municipality $municipality failed due to ${e.getMessage}.")
Vois ehkä napata täsmällisemmin virheitä mut ei varmaan hirveen akuuttia

2022-06-23 16:01 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/PavedRoadUpdateProcess.scala
> +  override def updateChangeSet(changeSet: ChangeSet) : Unit = {
Näissä UpdateProcess vaikuttaa olevan aika toistoa monesssa tiedostossa. Voisi katsoa sen vähentämistä. Ei nyt ihan akuuttia mutta helpostaa ylläpitoa tulevaisuudessa.

2022-07-07 10:43 UTC, SWJPTulijoki commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
> +import fi.liikennevirasto.digiroad2.asset.{HeightLimit, WidthLimit, CyclingAndWalking, _}
poistettu

2022-07-07 10:44 UTC, SWJPTulijoki commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LinearAssetUpdater.scala
> +object LinearAssetUpdater {
lisätty startup.sh:n lohko tämän ajoa varten

2022-07-20 13:07 UTC, SWJPTulijoki commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/PavedRoadUpdateProcess.scala
> +  override def updateChangeSet(changeSet: ChangeSet) : Unit = {
ok, nyt ajetaan updateChangeSet vain servicessä, ja tulee perinnän kautta prosesseille

2022-07-21 07:50 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/RoadWidthUpdateProcess.scala
> +  def updateByRoadLinks(typeId: Int, municipality: Int, roadLinks: Seq[RoadLink], changes: Seq[ChangeInfo]) = {
updateByRoadLinks on myös paljon toistoa ja tossa viellä toi type id joka viittais että josku ajatettu genererisenä, 
SpeedLimitUpdateProcess def updateByRoadLinks(municipality: Int, roadLinks: Seq[RoadLink], changes: Seq[ChangeInfo]) on toi type id poistettu hyym 
vois katsoa generalisointia

2022-08-15 06:19 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/HazMatTransportProhibitionUpdater.scala
> +    val (toInsert, toUpdate) = newLinearAssets.partition(_.id == 0L)
tää ei taida toimia merkkijonoille

2022-08-15 06:23 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LinearAssetUpdater.scala
> +        expiredAssetIds = existingAssets.filter(asset => removedLinkIds.contains(asset.linkId)).map(_.id).toSet.filterNot(_ == 0L),
(_ == 0L) nää tässä ja muuallakin pitäisi muuttaa varmaan toiseen muotoon. @Reetta

2022-08-15 06:23 UTC, SWJPTulijoki commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/HazMatTransportProhibitionUpdater.scala
> +    val (toInsert, toUpdate) = newLinearAssets.partition(_.id == 0L)
Eikös assettien id:t oo edelleen long? Vain tielinkkien id muuttuu?

2022-08-15 06:25 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LinearAssetUpdater.scala
> +    service.createWithoutTransaction(oldAsset.typeId, oldAsset.linkId, oldAsset.value.getOrElse(throw new IllegalStateException("Value of the old asset " + oldAsset.id + " of type " + oldAsset.typeId
voisko heittää vähän enter, vähän pitkä rivi

2022-08-15 06:28 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/ProhibitionUpdater.scala
> +    service.createWithoutTransaction(oldAsset.typeId, oldAsset.linkId, oldAsset.value.get, adjustment.sideCode.value, Measures(oldAsset.startMeasure, oldAsset.endMeasure), LinearAssetTypes.VvhGenerat
tässä myös, enter voi laittaa

2022-08-15 06:31 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/SpeedLimitUpdater.scala
> +class SpeedLimitUpdater(eventbus: DigiroadEventBus, roadLinkClient: RoadLinkClient, roadLinkService: RoadLinkService, service: SpeedLimitService) {
tää ei taida periä tota LinearAssetUpdater niin kuin noi muuut?

2022-08-15 06:33 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/SpeedLimitUpdater.scala
> +class SpeedLimitUpdater(eventbus: DigiroadEventBus, roadLinkClient: RoadLinkClient, roadLinkService: RoadLinkService, service: SpeedLimitService) {
varmaan vois muuttaa toimimaan samalla tavalla kuin noi toiset

2022-08-15 06:34 UTC, SWJPTulijoki commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/SpeedLimitUpdater.scala
> +class SpeedLimitUpdater(eventbus: DigiroadEventBus, roadLinkClient: RoadLinkClient, roadLinkService: RoadLinkService, service: SpeedLimitService) {
Ei. Toimii jonkun verran eri tavalla, eikä myöskään service puolella ollut vastaavan tyyppistä perintää.

2022-08-15 06:37 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/HazMatTransportProhibitionUpdater.scala
> +    val (toInsert, toUpdate) = newLinearAssets.partition(_.id == 0L)
okey joo nyt ajatus menee hitaalla

2022-08-15 06:39 UTC, SWJPTulijoki commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/SpeedLimitUpdater.scala
> +class SpeedLimitUpdater(eventbus: DigiroadEventBus, roadLinkClient: RoadLinkClient, roadLinkService: RoadLinkService, service: SpeedLimitService) {
Eka vastaus oli tohon ekaan kysymykseen. Muuttamiseen en osaa suoraan kommentoida. Tässä siirretty SpeedLimitServicen samuutusfunktiot tuonne updateriin. Jonkun verran ne toimii kyl eri tavalla kuin muissa asseteissa.

2022-08-15 11:17 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/SpeedLimitUpdater.scala
> +class SpeedLimitUpdater(eventbus: DigiroadEventBus, roadLinkClient: RoadLinkClient, roadLinkService: RoadLinkService, service: SpeedLimitService) {
Hyym toi Speedlimit Service vaatis vähän harmonisointia toimimaan samalla tyylliin kuin noi muutkin mut varmaan pitää katsoa sitä joskus myöhemmin jos tulee enemmän muutoksia siihen.

2022-08-15 14:51 UTC, sasuolanderSito commented on digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/SpeedLimitUpdater.scala
> +    val changeInfo = changes.find(c => c.oldId.getOrElse("") == oldId && c.newId.getOrElse("") == newId)
None olis varmaan myös kelvannut

2022-08-15 14:53 UTC, sasuolanderSito approved these changes
mennään nyt tällä ja parannellaan sit kun katotaan sitä tiekamu hommaa

2022-08-16 05:05 UTC, merged